### ISSUE TITLE
SecOps : Add semgrep secrets to project environment 

### ISSUE THREAD

**Issue by cooliscool** [Substancia/REACTive-cucumber-NEST#30]
For setting up automated code scanning for vulnerabilities, with each new PR merged, setup the following secrets in the project Github Actions Environment. 
Refer : https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

SEMGREP_APP_TOKEN 
SEMGREP_DEPLOYMENT_ID 

(shared via DM)

**Comment by Substancia** [comment]
Added as repository secrets for now (lmk if that's an issue right now), we can move it to environment secrets down the line.
